### ISSUE TITLE
Twitter API keys for @waku_org handle

### ISSUE THREAD

**Issue by hackyguru** [waku-org/metrics.waku.org#7]
To fetch the number of followers on twitter, we would require the following environment variables configured on vercel :

```
NEXT_PUBLIC_TWITTER_API_KEY="
NEXT_PUBLIC_TWITTER_USERNAME="waku_org"
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_ACCESS_TOKEN=
TWITTER_TOKEN_SECRET=
```

also, we only need 'read access' for the generated secrets

**Comment by fryorcraken** [comment]
@hackyguru looks like you need to sign for a developer account: https://developer.twitter.com/en/docs/twitter-api/getting-started/getting-access-to-the-twitter-api
